/**
 * SyntaxHighlighter
 * http://alexgorbatchev.com/SyntaxHighlighter
 *
 * SyntaxHighlighter is donationware. If you are using it, please donate.
 * http://alexgorbatchev.com/SyntaxHighlighter/donate.html
 *
 * @version
 * 3.0.83 (July 02 2010)
 *
 * @copyright
 * Copyright (C) 2004-2010 Alex Gorbatchev.
 *
 * @license
 * Dual licensed under the MIT and GPL licenses.
 */
var XRegExp;if(XRegExp)throw Error("can't load XRegExp twice in the same frame");
(function(){function s(b,a){if(!XRegExp.isRegExp(b))throw TypeError("type RegExp expected");var c=b._xregexp;b=XRegExp(b.source,t(b)+(a||""));c&&(b._xregexp={source:c.source,captureNames:c.captureNames?c.captureNames.slice(0):null});return b}function t(b){return(b.global?"g":"")+(b.ignoreCase?"i":"")+(b.multiline?"m":"")+(b.extended?"x":"")+(b.sticky?"y":"")}function n(b,a,c,e){var d=z.length,f,g,h;u=!0;try{for(;d--;)if(h=z[d],c&h.scope&&(!h.trigger||h.trigger.call(e))&&(h.pattern.lastIndex=a,(g=
h.pattern.exec(b))&&g.index===a)){f={output:h.handler.call(e,g,c),match:g};break}}catch(k){throw k;}finally{u=!1}return f}function w(b,a,c){if(Array.prototype.indexOf)return b.indexOf(a,c);for(c=c||0;c<b.length;c++)if(b[c]===a)return c;return-1}XRegExp=function(b,a){var c=[],e=XRegExp.OUTSIDE_CLASS,d=0,f,g;if(XRegExp.isRegExp(b)){if(void 0!==a)throw TypeError("can't supply flags when constructing one RegExp from another");return s(b)}if(u)throw Error("can't call the XRegExp constructor within token definition functions");
a=a||"";for(f={hasNamedCapture:!1,captureNames:[],hasFlag:function(c){return-1<a.indexOf(c)},setFlag:function(c){a+=c}};d<b.length;)(g=n(b,d,e,f))?(c.push(g.output),d+=g.match[0].length||1):(g=l.exec.call(A[e],b.slice(d)))?(c.push(g[0]),d+=g[0].length):(g=b.charAt(d),"["===g?e=XRegExp.INSIDE_CLASS:"]"===g&&(e=XRegExp.OUTSIDE_CLASS),c.push(g),d++);c=RegExp(c.join(""),l.replace.call(a,B,""));c._xregexp={source:b,captureNames:f.hasNamedCapture?f.captureNames:null};return c};XRegExp.version="1.5.0";XRegExp.INSIDE_CLASS=
1;XRegExp.OUTSIDE_CLASS=2;var x=/\$(?:(\d\d?|[$&`'])|{([$\w]+)})/g,B=/[^gimy]+|([\s\S])(?=[\s\S]*\1)/g,y=/^(?:[?*+]|{\d+(?:,\d*)?})\??/,u=!1,z=[],l={exec:RegExp.prototype.exec,test:RegExp.prototype.test,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},D=void 0===l.exec.call(/()??/,"")[1],v=function(){var b=/^/g;l.test.call(b,"");return!b.lastIndex}(),E=function(){var b=/x/g;l.replace.call("x",b,"");return!b.lastIndex}(),C=void 0!==RegExp.prototype.sticky,
A={};A[XRegExp.INSIDE_CLASS]=/^(?:\\(?:[0-3][0-7]{0,2}|[4-7][0-7]?|x[\dA-Fa-f]{2}|u[\dA-Fa-f]{4}|c[A-Za-z]|[\s\S]))/;A[XRegExp.OUTSIDE_CLASS]=/^(?:\\(?:0(?:[0-3][0-7]{0,2}|[4-7][0-7]?)?|[1-9]\d*|x[\dA-Fa-f]{2}|u[\dA-Fa-f]{4}|c[A-Za-z]|[\s\S])|\(\?[:=!]|[?*+]\?|{\d+(?:,\d*)?}\??)/;XRegExp.addToken=function(b,a,c,e){z.push({pattern:s(b,"g"+(C?"y":"")),handler:a,scope:c||XRegExp.OUTSIDE_CLASS,trigger:e||null})};XRegExp.cache=function(b,a){var c=b+"/"+(a||"");return XRegExp.cache[c]||(XRegExp.cache[c]=
XRegExp(b,a))};XRegExp.copyAsGlobal=function(b){return s(b,"g")};XRegExp.escape=function(b){return b.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")};XRegExp.execAt=function(b,a,c,e){a=s(a,"g"+(e&&C?"y":""));a.lastIndex=c=c||0;b=a.exec(b);return e?b&&b.index===c?b:null:b};XRegExp.freezeTokens=function(){XRegExp.addToken=function(){throw Error("can't run addToken after freezeTokens");}};XRegExp.isRegExp=function(b){return"[object RegExp]"===Object.prototype.toString.call(b)};XRegExp.iterate=function(b,
a,c,e){for(var d=s(a,"g"),f=-1,g;g=d.exec(b);)c.call(e,g,++f,b,d),d.lastIndex===g.index&&d.lastIndex++;a.global&&(a.lastIndex=0)};XRegExp.matchChain=function(b,a){return function e(b,f){var g=a[f].regex?a[f]:{regex:a[f]},h=s(g.regex,"g"),k=[],m;for(m=0;m<b.length;m++)XRegExp.iterate(b[m],h,function(a){k.push(g.backref?a[g.backref]||"":a[0])});return f!==a.length-1&&k.length?e(k,f+1):k}([b],0)};RegExp.prototype.apply=function(b,a){return this.exec(a[0])};RegExp.prototype.call=function(b,a){return this.exec(a)};
RegExp.prototype.exec=function(b){var a=l.exec.apply(this,arguments),c;if(a){!D&&1<a.length&&-1<w(a,"")&&(c=RegExp(this.source,l.replace.call(t(this),"g","")),l.replace.call(b.slice(a.index),c,function(){for(var c=1;c<arguments.length-2;c++)void 0===arguments[c]&&(a[c]=void 0)}));if(this._xregexp&&this._xregexp.captureNames)for(var e=1;e<a.length;e++)if(c=this._xregexp.captureNames[e-1])a[c]=a[e];!v&&this.global&&!a[0].length&&this.lastIndex>a.index&&this.lastIndex--}return a};v||(RegExp.prototype.test=
function(b){(b=l.exec.call(this,b))&&this.global&&!b[0].length&&this.lastIndex>b.index&&this.lastIndex--;return!!b});String.prototype.match=function(b){XRegExp.isRegExp(b)||(b=RegExp(b));if(b.global){var a=l.match.apply(this,arguments);b.lastIndex=0;return a}return b.exec(this)};String.prototype.replace=function(b,a){var c=XRegExp.isRegExp(b),e,d;if(c&&"string"===typeof a.valueOf()&&-1===a.indexOf("${")&&E)return l.replace.apply(this,arguments);c?b._xregexp&&(e=b._xregexp.captureNames):b+="";d="function"===
typeof a?l.replace.call(this,b,function(){if(e){arguments[0]=new String(arguments[0]);for(var f=0;f<e.length;f++)e[f]&&(arguments[0][e[f]]=arguments[f+1])}c&&b.global&&(b.lastIndex=arguments[arguments.length-2]+arguments[0].length);return a.apply(null,arguments)}):l.replace.call(this+"",b,function(){var c=arguments;return l.replace.call(a,x,function(a,b,d){if(b)switch(b){case "$":return"$";case "&":return c[0];case "`":return c[c.length-1].slice(0,c[c.length-2]);case "'":return c[c.length-1].slice(c[c.length-
2]+c[0].length);default:d="";b=+b;if(!b)return a;for(;b>c.length-3;)d=String.prototype.slice.call(b,-1)+d,b=Math.floor(b/10);return(b?c[b]||"":"$")+d}else{b=+d;if(b<=c.length-3)return c[b];b=e?w(e,d):-1;return-1<b?c[b+1]:a}})});c&&b.global&&(b.lastIndex=0);return d};String.prototype.split=function(b,a){if(!XRegExp.isRegExp(b))return l.split.apply(this,arguments);var c=this+"",e=[],d=0,f,g;if(void 0===a||0>+a)a=Infinity;else if(a=Math.floor(+a),!a)return[];for(b=XRegExp.copyAsGlobal(b);(f=b.exec(c))&&
!(b.lastIndex>d&&(e.push(c.slice(d,f.index)),1<f.length&&f.index<c.length&&Array.prototype.push.apply(e,f.slice(1)),g=f[0].length,d=b.lastIndex,e.length>=a));)b.lastIndex===f.index&&b.lastIndex++;d===c.length?l.test.call(b,"")&&!g||e.push(""):e.push(c.slice(d));return e.length>a?e.slice(0,a):e};XRegExp.addToken(/\(\?#[^)]*\)/,function(b){return l.test.call(y,b.input.slice(b.index+b[0].length))?"":"(?:)"});XRegExp.addToken(/\((?!\?)/,function(){this.captureNames.push(null);return"("});XRegExp.addToken(/\(\?<([$\w]+)>/,
function(b){this.captureNames.push(b[1]);this.hasNamedCapture=!0;return"("});XRegExp.addToken(/\\k<([\w$]+)>/,function(b){var a=w(this.captureNames,b[1]);return-1<a?"\\"+(a+1)+(isNaN(b.input.charAt(b.index+b[0].length))?"":"(?:)"):b[0]});XRegExp.addToken(/\[\^?]/,function(b){return"[]"===b[0]?"\\b\\B":"[\\s\\S]"});XRegExp.addToken(/^\(\?([imsx]+)\)/,function(b){this.setFlag(b[1]);return""});XRegExp.addToken(/(?:\s+|#.*)+/,function(b){return l.test.call(y,b.input.slice(b.index+b[0].length))?"":"(?:)"},
XRegExp.OUTSIDE_CLASS,function(){return this.hasFlag("x")});XRegExp.addToken(/\./,function(){return"[\\s\\S]"},XRegExp.OUTSIDE_CLASS,function(){return this.hasFlag("s")})})();"undefined"!=typeof exports&&(exports.XRegExp=XRegExp);
var SyntaxHighlighter=function(){function s(a,c){-1!=a.className.indexOf(c)||(a.className+=" "+c)}function t(a){return 0==a.indexOf("highlighter_")?a:"highlighter_"+a}function n(a,c,b){if(null==a)return null;var d=!0!=b?a.childNodes:[a.parentNode],f={"#":"id",".":"className"}[c.substr(0,1)]||"nodeName",g,h;g="nodeName"!=f?c.substr(1):c.toUpperCase();if(-1!=(a[f]||"").indexOf(g))return a;for(a=0;d&&a<d.length&&null==h;a++)h=n(d[a],c,b);return h}function w(a,c){var b={},d;for(d in a)b[d]=a[d];for(d in c)b[d]=
c[d];return b}function x(a,c,b,d){function f(a){a=a||window.event;a.target||(a.target=a.srcElement,a.preventDefault=function(){this.returnValue=!1});b.call(d||window,a)}a.attachEvent?a.attachEvent("on"+c,f):a.addEventListener(c,f,!1)}function B(a,c){var e=b.vars.discoveredBrushes,d=null;if(null==e){var e={},f;for(f in b.brushes){var g=b.brushes[f],d=g.aliases;if(null!=d)for(g.brushName=f.toLowerCase(),g=0;g<d.length;g++)e[d[g]]=f}b.vars.discoveredBrushes=e}d=b.brushes[e[a]];null==d&&!1!=c&&window.alert(b.config.strings.alert+
(b.config.strings.noBrush+a));return d}function y(a,c){for(var b=a.split("\n"),d=0;d<b.length;d++)b[d]=c(b[d],d);return b.join("\n")}function u(a,c){if(null==a||0==a.length||"\n"==a)return a;a=a.replace(/</g,"&lt;");a=a.replace(/ {2,}/g,function(a){for(var c="",f=0;f<a.length-1;f++)c+=b.config.space;return c+" "});null!=c&&(a=y(a,function(a){if(0==a.length)return"";var b="";a=a.replace(/^(&nbsp;| )+/,function(a){b=a;return""});return 0==a.length?b:b+'<code class="'+c+'">'+a+"</code>"}));return a}
function z(a,c){a.split("\n");for(var b="",d=0;50>d;d++)b+="                    ";return a=y(a,function(a){if(-1==a.indexOf("\t"))return a;for(var d=0;-1!=(d=a.indexOf("\t"));)a=a.substr(0,d)+b.substr(0,c-d%c)+a.substr(d+1,a.length);return a})}function l(a){return a.replace(/^\s+|\s+$/g,"")}function D(a,c){return a.index<c.index?-1:a.index>c.index?1:a.length<c.length?-1:a.length>c.length?1:0}function v(a,c){function e(a){return a[0]}for(var d=null,f=[],g=c.func?c.func:e;null!=(d=c.regex.exec(a));){var h=
g(d,c);"string"==typeof h&&(h=[new b.Match(h,d.index,c.css)]);f=f.concat(h)}return f}function E(a){var c=/(.*)((&gt;|&lt;).*)/;return a.replace(b.regexLib.url,function(a){var b="",f=null;if(f=c.exec(a))a=f[1],b=f[2];return'<a href="'+a+'">'+a+"</a>"+b})}function C(){for(var a=document.getElementsByTagName("script"),c=[],b=0;b<a.length;b++)"syntaxhighlighter"==a[b].type&&c.push(a[b]);return c}function A(a){a=a.target;var c=n(a,".syntaxhighlighter",!0);a=n(a,".container",!0);var b=document.createElement("textarea");
if(a&&c&&!n(a,"textarea")){t(c.id);s(c,"source");for(var d=a.childNodes,f=[],g=0;g<d.length;g++)f.push(d[g].innerText||d[g].textContent);f=f.join("\r");f=f.replace(/[^\u0000-\u007E]/g," ");b.appendChild(document.createTextNode(f));a.appendChild(b);b.focus();b.select();x(b,"blur",function(){b.parentNode.removeChild(b);c.className=c.className.replace("source","")})}}"undefined"!=typeof require&&"undefined"==typeof XRegExp&&(XRegExp=require("XRegExp").XRegExp);var b={defaults:{"class-name":"","first-line":1,
"pad-line-numbers":!1,highlight:null,title:null,"smart-tabs":!0,"tab-size":4,gutter:!0,toolbar:!0,"quick-code":!0,collapse:!1,"auto-links":!0,light:!1,"html-script":!1},config:{space:"&nbsp;",useScriptTags:!0,bloggerMode:!1,stripBrs:!1,tagName:"pre",strings:{expandSource:"expand source",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>About SyntaxHighlighter</title></head><body style="font-family:Geneva,Arial,Helvetica,sans-serif;background-color:#fff;color:#000;font-size:1em;text-align:center;"><div style="text-align:center;margin-top:1.5em;"><div style="font-size:xx-large;">SyntaxHighlighter</div><div style="font-size:.75em;margin-bottom:3em;"><div>version 3.0.83 (July 02 2010)</div><div><a href="http://alexgorbatchev.com/SyntaxHighlighter" target="_blank" style="color:#005896">http://alexgorbatchev.com/SyntaxHighlighter</a></div><div>JavaScript code syntax highlighter.</div><div>Copyright 2004-2010 Alex Gorbatchev.</div></div><div>If you like this script, please <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2930402" style="color:#005896">donate</a> to <br/>keep development active!</div></div></body></html>'}},
vars:{discoveredBrushes:null,highlighters:{}},brushes:{},regexLib:{multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"([^\\"\n]|\\.)*"/g,singleQuotedString:/'([^\\'\n]|\\.)*'/g,multiLineDoubleQuotedString:new XRegExp('"([^\\\\"]|\\\\.)*"',"gs"),multiLineSingleQuotedString:new XRegExp("'([^\\\\']|\\\\.)*'","gs"),xmlComments:/(&lt;|<)!--[\s\S]*?--(&gt;|>)/gm,url:/\w+:\/\/[\w-.\/?%&=:@;]*/g,phpScriptTags:{left:/(&lt;|<)\?=?/g,
right:/\?(&gt;|>)/g},aspScriptTags:{left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},toolbar:{getHtml:function(a){function c(a,c){return b.toolbar.getButtonHtml(a,c,b.config.strings[c])}for(var e='<div class="toolbar">',d=b.toolbar.items,f=d.list,g=0;g<f.length;g++)e+=(d[f[g]].getHtml||c)(a,f[g]);return e+"</div>"},getButtonHtml:function(a,c,b){return'<span><a href="#" class="toolbar_item command_'+c+" "+c+'">'+
b+"</a></span>"},handler:function(a){var c=a.target,e=c.className||"",c=n(c,".syntaxhighlighter",!0).id,c=b.vars.highlighters[t(c)],d="command",e=(d=RegExp(d+"_(\\w+)").exec(e))?d[1]:null;c&&e&&b.toolbar.items[e].execute(c);a.preventDefault()},items:{list:["expandSource","help"],expandSource:{getHtml:function(a){if(!0!=a.getParam("collapse"))return"";var c=a.getParam("title");return b.toolbar.getButtonHtml(a,"expandSource",c?c:b.config.strings.expandSource)},execute:function(a){a=document.getElementById(t(a.id));
a.className=a.className.replace("collapsed","")}},help:{execute:function(){var a;a="scrollbars=0"+(", left="+(screen.width-500)/2+", top="+(screen.height-250)/2+", width=500, height=250");a=a.replace(/^,/,"");a=window.open("","_blank",a);a.focus();var c=a.document;c.write(b.config.strings.aboutDialog);c.close();a.focus()}}}},findElements:function(a,c){var e;if(c)e=[c];else{e=document.getElementsByTagName(b.config.tagName);for(var d=[],f=0;f<e.length;f++)d.push(e[f]);e=d}d=[];b.config.useScriptTags&&
(e=e.concat(C()));if(0===e.length)return d;for(f=0;f<e.length;f++){for(var g=e[f],h=a,k=e[f].className,m=void 0,p={},q=new XRegExp("^\\[(?<values>(.*?))\\]$"),l=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");null!=(m=l.exec(k));){var r=m.value.replace(/^['"]|['"]$/g,"");null!=r&&q.test(r)&&(r=q.exec(r),r=0<r.values.length?r.values.split(/\s*,\s*/):[]);p[m.name]=r}g={target:g,params:w(h,p)};null!=g.params.brush&&d.push(g)}return d},highlight:function(a,
c){var e=this.findElements(a,c),d=null,f=b.config;if(0!==e.length)for(var g=0;g<e.length;g++){c=e[g];var h=c.target,k=c.params,m=k.brush,p;if(null!=m){if("true"==k["html-script"]||!0==b.defaults["html-script"])d=new b.HtmlScript(m),m="htmlscript";else if(d=B(m))d=new d;else continue;p=h.innerHTML;if(f.useScriptTags){var q=l(p),n=!1;0==q.indexOf("<![CDATA[")&&(q=q.substring(9),n=!0);var r=q.length;q.indexOf("]]\x3e")==r-3&&(q=q.substring(0,r-3),n=!0);p=n?q:p}""!=(h.title||"")&&(k.title=h.title);k.brush=
m;d.init(k);c=d.getDiv(p);""!=(h.id||"")&&(c.id=h.id);h.parentNode.replaceChild(c,h)}}},all:function(a){x(window,"load",function(){b.highlight(a)})}};b.all=b.all;b.highlight=b.highlight;b.Match=function(a,c,b){this.value=a;this.index=c;this.length=a.length;this.css=b;this.brushName=null};b.Match.prototype.toString=function(){return this.value};b.HtmlScript=function(a){function c(a,c){for(var b=0;b<a.length;b++)a[b].index+=c}var e=B(a),d,f=new b.brushes.Xml,g=this,h=["getDiv","getHtml","init"];if(null!=
e){d=new e;for(var k=0;k<h.length;k++)(function(){var a=h[k];g[a]=function(){return f[a].apply(f,arguments)}})();null==d.htmlScript?window.alert(b.config.strings.alert+(b.config.strings.brushNotHtmlScript+a)):f.regexList.push({regex:d.htmlScript.code,func:function(a){for(var b=a.code,f=[],g=d.regexList,h=a.index+a.left.length,k=d.htmlScript,l,n=0;n<g.length;n++)l=v(b,g[n]),c(l,h),f=f.concat(l);null!=k.left&&null!=a.left&&(l=v(a.left,k.left),c(l,a.index),f=f.concat(l));null!=k.right&&null!=a.right&&
(l=v(a.right,k.right),c(l,a.index+a[0].lastIndexOf(a.right)),f=f.concat(l));for(a=0;a<f.length;a++)f[a].brushName=e.brushName;return f}})}};b.Highlighter=function(){};b.Highlighter.prototype={getParam:function(a,c){var b=this.params[a],b=null==b?c:b,d={"true":!0,"false":!1}[b];return null==d?b:d},create:function(a){return document.createElement(a)},findMatches:function(a,b){var e=[];if(null!=a)for(var d=0;d<a.length;d++)"object"==typeof a[d]&&(e=e.concat(v(b,a[d])));return this.removeNestedMatches(e.sort(D))},
removeNestedMatches:function(a){for(var b=0;b<a.length;b++)if(null!==a[b])for(var e=a[b],d=e.index+e.length,f=b+1;f<a.length&&null!==a[b];f++){var g=a[f];if(null!==g)if(g.index>d)break;else g.index==e.index&&g.length>e.length?a[b]=null:g.index>=e.index&&g.index<d&&(a[f]=null)}return a},figureOutLineNumbers:function(a){var b=[],e=parseInt(this.getParam("first-line"));y(a,function(a,f){b.push(f+e)});return b},isLineHighlighted:function(a){var b=this.getParam("highlight",[]);"object"!=typeof b&&null==
b.push&&(b=[b]);a:{a=a.toString();var e;for(e=e=Math.max(0,0);e<b.length;e++)if(b[e]==a){b=e;break a}b=-1}return-1!=b},getLineHtml:function(a,b,e){a=["line","number"+b,"index"+a,"alt"+(0==b%2?1:2).toString()];this.isLineHighlighted(b)&&a.push("highlighted");0==b&&a.push("break");return'<div class="'+a.join(" ")+'">'+e+"</div>"},getLineNumbersHtml:function(a,c){var e="",d=a.split("\n").length,f=parseInt(this.getParam("first-line")),g=this.getParam("pad-line-numbers");!0==g?g=(f+d-1).toString().length:
!0==isNaN(g)&&(g=0);for(var h=0;h<d;h++){var k=c?c[h]:f+h,l;if(0==k)l=b.config.space;else{l=g;for(var p=k.toString();p.length<l;)p="0"+p;l=p}a=l;e+=this.getLineHtml(h,k,a)}return e},getCodeLinesHtml:function(a,c){a=l(a);var e=a.split("\n");this.getParam("pad-line-numbers");var d=parseInt(this.getParam("first-line"));a="";for(var f=this.getParam("brush"),g=0;g<e.length;g++){var h=e[g],k=/^(&nbsp;|\s)+/.exec(h),m=null,p=c?c[g]:d+g;null!=k&&(m=k[0].toString(),h=h.substr(m.length),m=m.replace(" ",b.config.space));
h=l(h);0==h.length&&(h=b.config.space);a+=this.getLineHtml(g,p,(null!=m?'<code class="'+f+' spaces">'+m+"</code>":"")+h)}return a},getTitleHtml:function(a){return a?"<caption>"+a+"</caption>":""},getMatchesHtml:function(a,b){function e(a){return(a=a?a.brushName||g:g)?a+" ":""}for(var d=0,f="",g=this.getParam("brush",""),h=0;h<b.length;h++){var k=b[h],l;null!==k&&0!==k.length&&(l=e(k),f+=u(a.substr(d,k.index-d),l+"plain")+u(k.value,l+k.css),d=k.index+k.length+(k.offset||0))}return f+=u(a.substr(d),
e()+"plain")},getHtml:function(a){var c="",e=["syntaxhighlighter"],d;!0==this.getParam("light")&&(this.params.toolbar=this.params.gutter=!1);className="syntaxhighlighter";!0==this.getParam("collapse")&&e.push("collapsed");!1==(gutter=this.getParam("gutter"))&&e.push("nogutter");e.push(this.getParam("class-name"));e.push(this.getParam("brush"));a=a.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,"").replace(/\r/g," ");c=this.getParam("tab-size");if(!0==this.getParam("smart-tabs"))a=z(a,c);else{for(var f="",g=0;g<
c;g++)f+=" ";a=a.replace(/\t/g,f)}a:{c=a;f=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;!0==b.config.bloggerMode&&(c=c.replace(f,"\n"));!0==b.config.stripBrs&&(c=c.replace(f,""));for(var c=c.split("\n"),f=/^\s*/,g=1E3,h=0;h<c.length&&0<g;h++){var k=c[h];if(0!=l(k).length){k=f.exec(k);if(null==k)break a;g=Math.min(k[0].length,g)}}if(0<g)for(h=0;h<c.length;h++)c[h]=c[h].substr(g);a=c.join("\n")}gutter&&(d=this.figureOutLineNumbers(a));c=this.findMatches(this.regexList,a);c=this.getMatchesHtml(a,c);c=this.getCodeLinesHtml(c,
d);this.getParam("auto-links")&&(c=E(c));"undefined"!=typeof navigator&&navigator.userAgent&&navigator.userAgent.match(/MSIE/)&&e.push("ie");return'<div id="'+t(this.id)+'" class="'+e.join(" ")+'">'+(this.getParam("toolbar")?b.toolbar.getHtml(this):"")+'<table border="0" cellpadding="0" cellspacing="0">'+this.getTitleHtml(this.getParam("title"))+"<tbody><tr>"+(gutter?'<td class="gutter">'+this.getLineNumbersHtml(a)+"</td>":"")+'<td class="code"><div class="container">'+c+"</div></td></tr></tbody></table></div>"},
getDiv:function(a){null===a&&(a="");this.code=a;var c=this.create("div");c.innerHTML=this.getHtml(a);this.getParam("toolbar")&&x(n(c,".toolbar"),"click",b.toolbar.handler);this.getParam("quick-code")&&x(n(c,".code"),"dblclick",A);return c},init:function(a){this.id=""+Math.round(1E6*Math.random()).toString();b.vars.highlighters[t(this.id)]=this;this.params=w(b.defaults,a||{});!0==this.getParam("light")&&(this.params.toolbar=this.params.gutter=!1)},getKeywords:function(a){a=a.replace(/^\s+|\s+$/g,"").replace(/\s+/g,
"|");return"\\b(?:"+a+")\\b"},forHtmlScript:function(a){this.htmlScript={left:{regex:a.left,css:"script"},right:{regex:a.right,css:"script"},code:new XRegExp("(?<left>"+a.left.source+")(?<code>.*?)(?<right>"+a.right.source+")","sgi")}}};return b}();"undefined"!=typeof exports&&(exports.SyntaxHighlighter=SyntaxHighlighter);